# Generated by Django 4.1.3 on 2023-01-22 20:44

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('subtitulo', models.CharField(max_length=200, verbose_name='subtitulo')),
                ('descripcion', models.CharField(max_length=150, verbose_name='descripcion')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('img', models.URLField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
