# Generated by Django 4.1.3 on 2023-01-22 20:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=160, verbose_name='title')),
                ('descr', models.CharField(max_length=250, verbose_name='description')),
                ('relleno', ckeditor.fields.RichTextField()),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='fecha')),
                ('subtitle', models.CharField(max_length=230, verbose_name='subtitle')),
                ('imagen', models.URLField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
